spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

oauth2:
  Google:
    clientId: 791533454342-l79c8n40c32dbi3f1rrk5q2feeeq8m0j.apps.googleusercontent.com
    clientSecret: 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
    redirectUri: http://127.0.0.1:8080/login/oauth2/code/google
    authorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenUri: https://oauth2.googleapis.com/token
    userInfoUri: https://www.googleapis.com/oauth2/userinfo
    jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
    clientName: Google
    registrationId: google